apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-tooling
bases:
- ../../base

commonLabels:
  env: prod-tooling

resources:
  - namespace.yaml

patches:
  - deployment.yaml